services:
  f0w-nextjs:
    build: .
    environment:
      - NODE_ENV
      - LASTFM_USER
      - TRACK_LIMIT
      - LASTFM_BASE_URL
      - LASTFM_API_KEY
      - GITHUB_USER
      - GITHUB_API_KEY
      - TELEGRAM_API_KEY
      - TELEGRAM_CHAT_ID
      - CANONICAL_URL
      - UMAMI_SCRIPT_URL
      - UMAMI_WEBSITE_ID
      - NEXT_PUBLIC_BASE_URL
      - DATABASE_URL
      - NEXT_PUBLIC_IMAGES_URL
      - WEBRING_PUBLIC_URL
      - WEBRING_USER_ID
    ports:
      - '16000:16000'
