services:
  f0w-nextjs:
    build: .
    environment:
      - NODE_ENV=${NODE_ENV}
      - LASTFM_USER=${LASTFM_USER}
      - TRACK_LIMIT=${TRACK_LIMIT}
      - LASTFM_BASE_URL=${LASTFM_BASE_URL}
      - LASTFM_API_KEY=${LASTFM_API_KEY}
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_API_KEY=${GITHUB_API_KEY}
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - CANONICAL_URL=${CANONICAL_URL}
      - UMAMI_SCRIPT_URL=${UMAMI_SCRIPT_URL}
      - UMAMI_WEBSITE_ID=${UMAMI_WEBSITE_ID}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_IMAGES_URL=${NEXT_PUBLIC_IMAGES_URL}
      - WEBRING_PUBLIC_URL=${WEBRING_PUBLIC_URL}
      - WEBRING_USER_ID=${WEBRING_USER_ID}
    ports:
      - "${PORT}:${PORT}"
